config:
  selfUrl: # 
  gatewayUrl: # 
  authServer:
    authority: # http://moduletest-st-authserver
    requireHttpsMetadata: # "false"
    isOnK8s: # "true"
    metaAddress: # http://moduletest-st-authserver
  dotnetEnv: # 
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

ingress:
  host: # moduletest-st-public-web
  tlsSecret: moduletest-tls

image:
  repository: mycompanyname/moduletest-app-public-web
  tag: latest
  pullPolicy: IfNotPresent

env: {}