config:
  selfUrl: # https://identity.moduletest.dev
  corsOrigins: # https://moduletest-st-gateway-web,https://moduletest-st-gateway-public-web
  connectionStrings:
    identityService: #
    administrationService: #
    saasService: #
  authServer:
    authority: # http://moduletest-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.moduletest.dev/.well-known/openid-configuration
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

# Seeded applications and resources 
openIdDict:
  applications:
    authServerRootUrl: #
    angularRootUrl: #
    webRootUrl: #
    blazorRootUrl: #
    blazorServerRootUrl: #
    publicWebRootUrl: #
    webGatewayRootUrl: #
    publicWebGatewayRootUrl: #
  resources:  
    accountServiceRootUrl: #
    administrationServiceRootUrl: #
    identityServiceRootUrl: #
    saasServiceRootUrl: #
    productServiceRootUrl: #

ingress:
  host: identity.moduletest.dev
  tlsSecret: moduletest-tls

image:
  repository: mycompanyname/moduletest-service-identity
  tag: latest
  pullPolicy: IfNotPresent

env: {}
