version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    networks:
      - moduletest-network
      
  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - moduletest-network
      
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    # volumes:
    #   - esdata:/usr/share/elasticsearch/data
    networks:
      - moduletest-network
      
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.5.3
    depends_on:
      - elasticsearch
    networks:
      - moduletest-network
    
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - moduletest-network
 
  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ../grafana/storage:/var/lib/grafana
    networks:
      - moduletest-network
      
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../prometheus/storage:/prometheus
    networks:
      - moduletest-network
      
volumes:
  esdata:
  sqldata:
networks:
  moduletest-network:
    external: true