config:
  selfUrl: # https://administration.moduletest.dev
  corsOrigins: #
  connectionStrings:
    administrationService: #
    saasService: #
  authServer:
    authority: # http://moduletest-st-authserver
    requireHttpsMetadata: "false"
    metadataAddress: # http://admin.moduletest.dev/.well-known/openid-configuration
    swaggerClientId: WebGateway_Swagger
  remoteServices:
    abpIdentityBaseUrl: #
    useCurrentToken: "false"
  dotnetEnv: #
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

synchedCommunication:
  authority: # https://admin.moduletest.dev
  requireHttps: #
  validateIssuerName: #
  validateEndpoints: #

ingress:
  host: # moduletest-st-administration
  tlsSecret: moduletest-tls

image:
  repository: mycompanyname/moduletest-service-administration
  tag: latest
  pullPolicy: IfNotPresent

env: {}
