# auth-server sub-chart override
authserver:
  config:
    selfUrl: https://authserver-demo-ms.abp.io
    corsOrigins: https://gateway-web-demo-ms.abp.io,https://gateway-web-public-demo-ms.abp.io,https://identity-demo-ms.abp.io,https://administration-demo-ms.abp.io,https://saas-demo-ms.abp.io,https://product-demo-ms.abp.io
    allowedRedirectUrls: http://demo-ms-angular,https://angular-demo-ms.abp.io,http://demo-ms-blazor,https://blazor-demo-ms.abp.io
    identityService:
      connString: "Server=demo-ms-sqldb,1433;Database=ModuleTest_Identity;User Id=sa;password=myPassw@rd; TrustServerCertificate=True;"
    administrationService:
      connString: "Server=demo-ms-sqldb,1433;Database=ModuleTest_Administration;User Id=sa;password=myPassw@rd; TrustServerCertificate=True;"
    saasService:
      connString: "Server=demo-ms-sqldb,1433;Database=ModuleTest_Saas;User Id=sa;password=myPassw@rd; TrustServerCertificate=True;"
    authServer:
      authority: http://demo-ms-authserver
      requireHttpsMetadata: "false"
      swaggerClientId: WebGateway_Swagger
    dotnetEnv: Staging
    redisHost: demo-ms-redis
    rabbitmqHost: demo-ms-rabbitmq
    elasticsearchUrl: http://demo-ms-elasticsearch:9200
    AbpLicenseCode: "*" 

  ingress:
    host: authserver-demo-ms.abp.io
  image:
    repository: volosoft.azurecr.io/demo-ms/authserver
    tag: "20230526.7"

# identity-service sub-chart override
identity:
  config:
    selfUrl: https://identity-demo-ms.abp.io
    corsOrigins: https://gateway-web-demo-ms.abp.io
    connectionStrings:
      identityService: "Server=demo-ms-sqldb,1433;Database=ModuleTest_Identity;User Id=sa;password=myPassw@rd; TrustServerCertificate=True;"
      administrationService: "Server=demo-ms-sqldb,1433;Database=ModuleTest_Administration;User Id=sa;password=myPassw@rd; TrustServerCertificate=True;"
      saasService: "Server=demo-ms-sqldb,1433;Database=ModuleTest_Saas;User Id=sa;password=myPassw@rd; TrustServerCertificate=True;"
    authServer:
      authority: http://demo-ms-authserver
      requireHttpsMetadata: "false"
    dotnetEnv: Staging
    redisHost: demo-ms-redis
    rabbitmqHost: demo-ms-rabbitmq
    elasticsearchUrl: http://demo-ms-elasticsearch:9200
    AbpLicenseCode: "*" 

  openIdDict: #Seede applications and resources
    applications:
      authServerRootUrl: https://authserver-demo-ms.abp.io/
      angularRootUrl: https://angular-demo-ms.abp.io/
      webRootUrl: https://web-demo-ms.abp.io/
      blazorRootUrl: https://blazor-demo-ms.abp.io/
      blazorServerRootUrl: https://blazor-server-demo-ms.abp.io/
      publicWebRootUrl: https://demo-ms.abp.io/
      webGatewayRootUrl: https://gateway-web-demo-ms.abp.io/
      publicWebGatewayRootUrl: https://gateway-web-public-demo-ms.abp.io/ 
    resources:  
      accountServiceRootUrl: https://authserver-demo-ms.abp.io/
      administrationServiceRootUrl: https://administration-demo-ms.abp.io/
      identityServiceRootUrl: https://identity-demo-ms.abp.io/
      saasServiceRootUrl: https://saas-demo-ms.abp.io/
      productServiceRootUrl: https://product-demo-ms.abp.io/
  ingress:
    host: identity-demo-ms.abp.io
  image:
    repository: volosoft.azurecr.io/demo-ms/identity
    tag: "20230526.7"

# administration-service sub-chart override
administration:
  config:
    selfUrl: https://administration-demo-ms.abp.io
    corsOrigins: https://gateway-web-demo-ms.abp.io,https://gateway-web-public-demo-ms.abp.io
    connectionStrings:
      administrationService: "Server=demo-ms-sqldb,1433;Database=ModuleTest_Administration;User Id=sa;password=myPassw@rd; TrustServerCertificate=True;"
      saasService: "Server=demo-ms-sqldb,1433;Database=ModuleTest_Saas;User Id=sa;password=myPassw@rd; TrustServerCertificate=True;"    
    authServer:
      authority: http://demo-ms-authserver
      requireHttpsMetadata: "false"
      swaggerClientId: WebGateway_Swagger
    remoteServices:
      abpIdentityBaseUrl: https://demo-ms-identity
      useCurrentToken: "false"   
    dotnetEnv: Staging
    redisHost: demo-ms-redis
    rabbitmqHost: demo-ms-rabbitmq
    elasticsearchUrl: http://demo-ms-elasticsearch:9200
    AbpLicenseCode: "*" 

  synchedCommunication: # Used for server-to-server (client-credentials) communication with identityService for user permissions
    authority: https://authserver-demo-ms.abp.io
  ingress:
    host: administration-demo-ms.abp.io
  image:
    repository: volosoft.azurecr.io/demo-ms/administration
    tag: "20230526.7"

# saas-service sub-chart override
saas:
  config:
    selfUrl: https://saas-demo-ms.abp.io
    corsOrigins: https://gateway-web-demo-ms.abp.io
    connectionStrings:
      administrationService: "Server=demo-ms-sqldb,1433;Database=ModuleTest_Administration;User Id=sa;password=myPassw@rd; TrustServerCertificate=True;"
      saasService: "Server=demo-ms-sqldb,1433;Database=ModuleTest_Saas;User Id=sa;password=myPassw@rd; TrustServerCertificate=True;"
    authServer:
      authority: http://demo-ms-authserver
      requireHttpsMetadata: "false"
      swaggerClientId: WebGateway_Swagger
    dotnetEnv: Staging
    redisHost: demo-ms-redis
    rabbitmqHost: demo-ms-rabbitmq
    elasticsearchUrl: http://demo-ms-elasticsearch:9200
    AbpLicenseCode: "*" 

  ingress:
    host: saas-demo-ms.abp.io
  image:
    repository: volosoft.azurecr.io/demo-ms/saas
    tag: "20230526.7"  

# product-service sub-chart override
product:
  config:
    selfUrl: https://product-demo-ms.abp.io
    corsOrigins: https://gateway-web-demo-ms.abp.io,https://gateway-web-public-demo-ms.abp.io
    connectionStrings:
      productService: "Server=demo-ms-sqldb,1433;Database=ModuleTest_ProductService;User Id=sa;password=myPassw@rd; TrustServerCertificate=True;"
      administrationService: "Server=demo-ms-sqldb,1433;Database=ModuleTest_Administration;User Id=sa;password=myPassw@rd; TrustServerCertificate=True;"
      saasService: "Server=demo-ms-sqldb,1433;Database=ModuleTest_Saas;User Id=sa;password=myPassw@rd; TrustServerCertificate=True;"
    authServer:
      authority: http://demo-ms-authserver
      requireHttpsMetadata: "false"
      swaggerClientId: WebGateway_Swagger
    dotnetEnv: Staging
    redisHost: demo-ms-redis
    rabbitmqHost: demo-ms-rabbitmq
    elasticsearchUrl: http://demo-ms-elasticsearch:9200
    AbpLicenseCode: "*" 

  ingress:
    host: product-demo-ms.abp.io
  image:
    repository: volosoft.azurecr.io/demo-ms/product
    tag: "20230526.7"

# gateway-web sub-chart override
gateway-web:
  config:
    selfUrl: https://gateway-web-demo-ms.abp.io
    corsOrigins: https://angular-demo-ms.abp.io,https://blazor-demo-ms.abp.io
    globalConfigurationBaseUrl: http://demo-ms-gateway-web
    authServer:
      authority: http://demo-ms-authserver
      requireHttpsMetadata: "false"
      swaggerClientId: WebGateway_Swagger
    dotnetEnv: Staging
    redisHost: demo-ms-redis
    rabbitmqHost: demo-ms-rabbitmq
    elasticsearchUrl: http://demo-ms-elasticsearch:9200
    AbpLicenseCode: "*" 

  reRoutes:
    accountService:
      schema: http
      host: demo-ms-authserver
      port: 80
    identityService:
      schema: # http
      host: demo-ms-identity
      port: 80
    administrationService:
      schema: http
      host: demo-ms-administration
      port: 80
    saasService:
      schema: # http
      host: demo-ms-saas
      port: 80
    productService:
      schema: http
      host: demo-ms-product
      port: 80  
  ingress:
    host: gateway-web-demo-ms.abp.io
  image:
    repository: volosoft.azurecr.io/demo-ms/webgateway
    tag: "20230526.7"
    pullPolicy: IfNotPresent

# gateway-web-public sub-chart override
gateway-web-public:
  config:
    selfUrl: https://gateway-web-public-demo-ms.abp.io
    globalConfigurationBaseUrl: http://demo-ms-gateway-web-public
    authServer:
      authority: http://demo-ms-authserver
      requireHttpsMetadata: "false"
      swaggerClientId: WebGateway_Swagger
      swaggerClientSecret: "1q2w3e*"
    dotnetEnv: Staging 
    redisHost: demo-ms-redis
    rabbitmqHost: demo-ms-rabbitmq
    elasticsearchUrl: http://demo-ms-elasticsearch:9200
    AbpLicenseCode: "*" 

  reRoutes:
    accountService:
      schema: http
      host: demo-ms-authserver
      port: 80
    saasService:
      schema: http
      host: demo-ms-saas
      port: 80
    administrationService:
      schema: http
      host: demo-ms-administration
      port: 80
    productService:
      schema: http
      host: demo-ms-product
      port: 80  
  ingress:
    host: gateway-web-public-demo-ms.abp.io
    #tlsSecret: moduletest-tls
  image:
    repository: volosoft.azurecr.io/demo-ms/publicwebgateway
    tag: "20230526.7"
    pullPolicy: IfNotPresent

# kibana:
#   config:
#     elasticsearchUrl: http://demo-ms-elasticsearch:9200

# dbmigrator sub-chart override
dbmigrator:
  config:
    connectionStrings:
      identityService: "Server=demo-ms-sqldb,1433;Database=ModuleTest_Identity;User Id=sa;password=myPassw@rd; TrustServerCertificate=True;"
      administrationService: "Server=demo-ms-sqldb,1433;Database=ModuleTest_Administration;User Id=sa;password=myPassw@rd; TrustServerCertificate=True;"
      saasService: "Server=demo-ms-sqldb,1433;Database=ModuleTest_Saas;User Id=sa;password=myPassw@rd; TrustServerCertificate=True;"
      productService: "Server=demo-ms-sqldb,1433;Database=ModuleTest_ProductService;User Id=sa;password=myPassw@rd; TrustServerCertificate=True;"
    dotnetEnv: Staging
    AbpLicenseCode: "*"
  openIdDict:
    applications:
      authServerRootUrl: https://authserver-demo-ms.abp.io/
      angularRootUrl: https://angular-demo-ms.abp.io/
      webRootUrl: https://web-demo-ms.abp.io/
      blazorRootUrl: https://blazor-demo-ms.abp.io/
      blazorServerRootUrl: https://blazor-server-demo-ms.abp.io/
      publicWebRootUrl: https://demo-ms.abp.io/
      webGatewayRootUrl: https://gateway-web-demo-ms.abp.io/
      publicWebGatewayRootUrl: https://gateway-web-public-demo-ms.abp.io/ 
    resources:  
      accountServiceRootUrl: https://authserver-demo-ms.abp.io/
      administrationServiceRootUrl: https://administration-demo-ms.abp.io/
      identityServiceRootUrl: https://identity-demo-ms.abp.io/
      saasServiceRootUrl: https://saas-demo-ms.abp.io/
      productServiceRootUrl: https://product-demo-ms.abp.io/
    
  image:
    repository: volosoft.azurecr.io/demo-ms/migrator
    tag: "20230526.7"
    pullPolicy: IfNotPresent  

# Public Web application sub-chart override
publicweb:
  config:
    selfUrl: https://demo-ms.abp.io
    gatewayUrl: http://demo-ms-gateway-web-public
    authServer:
      authority: https://authserver-demo-ms.abp.io # should be domain on production (https://auth.mydomain.com)
      requireHttpsMetadata: "false"
      isOnK8s: "true"
      metaAddress: http://demo-ms-authserver # should be container on production (http://moduletest-az-authserver)
    dotnetEnv: Staging 
    redisHost: demo-ms-redis
    rabbitmqHost: demo-ms-rabbitmq
    elasticsearchUrl: http://demo-ms-elasticsearch:9200
    AbpLicenseCode: "*" 

  ingress:
    host: demo-ms.abp.io
    #tlsSecret: moduletest-tls
  image:
    repository: volosoft.azurecr.io/demo-ms/publicweb
    tag: "20230526.7"
    pullPolicy: IfNotPresent
# Angular back-office application sub-chart override

# angular:
#   config:
#     selfUrl: https://angular-demo-ms.abp.io
#     gatewayUrl: https://gateway-web-demo-ms.abp.io
#     authServer:
#       authority: http://demo-ms-authserver
#       requireHttpsMetadata: "false"
#       responseType: "code"
#       strictDiscoveryDocumentValidation: false
#       skipIssuerCheck: true
#   ingress:
#     host: angular-demo-ms.abp.io
#     #tlsSecret: moduletest-tls
#   image:
#     repository: volosoft.azurecr.io/demo-ms/angular
#     tag: "20230526.7"
#     pullPolicy: IfNotPresent

# Default values for ModuleTest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
    agentpool: demopool

tolerations: []

affinity: {}
