config:
  selfUrl: # https://authserver.moduletest.dev
  corsOrigins: #
  allowedRedirectUrls: #
  disablePii: #
  identityService:
    connString: # 
  administrationService:
    connString: # 
  saasService:
    connString: #     
  authServer:
    authority: #
    requireHttpsMetadata: #
    swaggerClientId: #
  dotnetEnv: # 
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

ingress:
  host: authserver.moduletest.dev
  tlsSecret: moduletest-tls

image:
  repository: mycompanyname/moduletest-app-authserver
  tag: latest
  pullPolicy: IfNotPresent

env: {}
    