apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
data:
  appsettings.json: |-
    {
    "App": {
        "SelfUrl": "{{ .Values.config.selfUrl }}"
    },
    "AuthServer": {
        "Authority": "{{ .Values.config.authServer.authority }}",
        "ClientId": "Blazor",
        "ResponseType": "{{ .Values.config.authServer.responseType }}"
    },
    "RemoteServices": {
        "Default": {
        "BaseUrl": "{{ .Values.config.gatewayUrl }}"
        },
        "AbpAccountPublic": {
        "BaseUrl": "{{ .Values.config.gatewayUrl }}"
        }
    }
    }