config:
  selfUrl: # https://product.moduletest.dev
  corsOrigins: #
  connectionStrings:
    productService: #
    administrationService: #
    saasService: #
  authServer:
    authority: # http://moduletest-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.moduletest.dev/.well-known/openid-configuration
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

ingress:
  host: product.moduletest.dev
  tlsSecret: moduletest-tls

image:
  repository: mycompanyname/moduletest-service-product
  tag: latest
  pullPolicy: IfNotPresent

env: {}      