config:
  selfUrl: # https://web.moduletest.dev
  gatewayUrl: # http://moduletest-st-gateway-web
  authServer:
    authority: # https://authserver.moduletest.dev
    requireHttpsMetadata: # "false"
    isOnK8s: # "true"
    metaAddress: # http://moduletest-st-authserver
  dotnetEnv: # 
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

ingress:
  host: # web.moduletest.dev
  tlsSecret: moduletest-tls

image:
  repository: mycompanyname/moduletest-app-web
  tag: latest
  pullPolicy: IfNotPresent

env: {}